# -*- coding: utf-8 -*-
"""Agentipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWOhne9kdEGKa4TvHMrErcyIQW-I_gCT
"""

!pip install langchain langchain-groq langchain-community langchain-chroma langchain-huggingface langchain-text-splitters chromadb sentence-transformers transformers torch -q

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage, ToolMessage, SystemMessage
from langchain_core.tools import tool
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma
from langchain_core.runnables import RunnablePassthrough
from transformers import pipeline

print("All imports done.")

# LLM
llm = ChatGroq(
    api_key="api_key",
    model="llama-3.3-70b-versatile"
)

# Test queries
queries = [
    "My transaction TXN002 failed but money was deducted from my HDFC account",
    "I need to check my account ACC001 status",
    "How long does a refund take?",
    "My account has been suspended, what do I do?"
]

# Create the policy document
policy_text = """
CUSTOMER SERVICE POLICY DOCUMENT
Company: FinServe Solutions

REFUND POLICY:
- Customers can request a refund within 30 days of purchase.
- Refunds are processed within 3-5 business days.
- Refunds are only applicable for failed transactions or duplicate charges.
- Customers must provide transaction ID and bank statement as proof.
- Refunds above 10,000 rupees require manager approval.

ACCOUNT SUSPENSION POLICY:
- Accounts are suspended after 3 consecutive failed login attempts.
- Suspended accounts can be reactivated by verifying government issued ID.
- Accounts inactive for more than 6 months are automatically suspended.
- Customers with outstanding dues cannot reactivate accounts until dues are cleared.

TRANSACTION DISPUTE POLICY:
- Disputes must be raised within 7 days of the transaction.
- Dispute resolution takes 5-10 business days.
- Customers will be notified via email at each stage of the dispute.
- If dispute is resolved in customer's favour, amount is credited within 2 business days.

CUSTOMER SUPPORT POLICY:
- Support is available 24/7 via chat and email.
- Phone support is available Monday to Friday, 9am to 6pm.
- Average response time for email is 24 hours.
- Priority support is available for premium customers.
"""

with open("policy.txt", "w") as f:
    f.write(policy_text)

# Load, split, embed, store
loader = TextLoader("policy.txt")
documents = loader.load()

splitter = RecursiveCharacterTextSplitter(chunk_size=200, chunk_overlap=50)
chunks = splitter.split_documents(documents)

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

vectorstore = Chroma.from_documents(documents=chunks, embedding=embeddings)
retriever = vectorstore.as_retriever(search_kwargs={"k": 3})

print(f"RAG ready. {len(chunks)} chunks stored.")

@tool
def check_refund_status(transaction_id: str) -> str:
    """Check the refund status using a transaction ID starting with TXN."""
    refunds = {
        "TXN001": "Refund processed. Amount will reflect in 3-5 business days.",
        "TXN002": "Refund pending. Under review by the payments team.",
        "TXN003": "Refund rejected. Insufficient evidence provided."
    }
    return refunds.get(transaction_id, "Transaction ID not found.")

@tool
def get_account_status(account_id: str) -> str:
    """Get the account status using an account ID starting with ACC."""
    accounts = {
        "ACC001": "Account active. No issues detected.",
        "ACC002": "Account suspended due to suspicious activity.",
        "ACC003": "Account under verification. Limited access enabled."
    }
    return accounts.get(account_id, "Account ID not found.")

llm_with_tools = llm.bind_tools([check_refund_status, get_account_status])

print("Tools ready.")

history = []

print("Memory ready.")

sentiment_pipeline = pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english"
)

intent_pipeline = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli"
)

ner_pipeline = pipeline(
    "ner",
    model="dbmdz/bert-large-cased-finetuned-conll03-english",
    aggregation_strategy="simple"
)

intents = ["billing issue", "account management", "technical support", "refund request", "general inquiry"]

print("NLP pipelines ready.")

def run_customer_service_agent(query, history=[]):

    # Step 1 — NLP Analysis
    sentiment = sentiment_pipeline(query)[0]
    intent = intent_pipeline(query, candidate_labels=intents)
    entities = ner_pipeline(query)

    # Step 2 — RAG Retrieval
    docs = retriever.invoke(query)
    context = "\n\n".join(doc.page_content for doc in docs)

    # Step 3 — Build enriched system message
    system_message = f"""You are a helpful customer service agent for FinServe Solutions.

Customer sentiment: {sentiment['label']} (confidence: {sentiment['score']:.2f})
Detected intent: {intent['labels'][0]}
Entities mentioned: {[e['word'] for e in entities] if entities else 'None'}

Relevant policy context:
{context}

Instructions:
- Use the policy context to answer accurately
- If customer is NEGATIVE, be extra empathetic
- Use tools if customer mentions a transaction ID or account ID
- Only answer from the policy context provided
"""

    # Step 4 — Add query to history
    history.append(HumanMessage(content=query))

    # Step 5 — LLM thinks, tool loop
    response = llm_with_tools.invoke([
        SystemMessage(content=system_message),
        *history
    ])

    while response.tool_calls:
        history.append(response)
        for tool_call in response.tool_calls:
            if tool_call['name'] == 'check_refund_status':
                tool_result = check_refund_status.invoke(tool_call['args'])
            elif tool_call['name'] == 'get_account_status':
                tool_result = get_account_status.invoke(tool_call['args'])
            history.append(ToolMessage(
                content=tool_result,
                tool_call_id=tool_call['id']
            ))
        response = llm_with_tools.invoke([
            SystemMessage(content=system_message),
            *history
        ])

    # Step 6 — Update history with response
    history.append(AIMessage(content=response.content))

    return response.content, sentiment, intent['labels'][0], entities, history

history = []

for query in queries:
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print(f"User: {query}")

    response, sentiment, intent, entities, history = run_customer_service_agent(query, history)

    print(f"Sentiment : {sentiment['label']} ({sentiment['score']:.2f})")
    print(f"Intent    : {intent}")
    print(f"Entities  : {[e['word'] for e in entities] if entities else 'None'}")
    print(f"Agent     : {response}")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")

